### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by 86196831** [imsyy/vitepress-theme-curve#18]
在本地可以打开，部署到vecrel和cf上都失败

**Comment by PuppetRuler** [comment]
删些链接,删到npm run build成功🤪

**Comment by 86196831** [comment]
> 删些链接，删到npm run build成功 🤪
您好，请问下什么意思，删哪里的链接？

**Comment by PuppetRuler** [comment]
报错是一堆Image Error,是图床做了校验,当时我是本地npm run build去查哪些需要删的,删完后能build成功就能部署了

**Comment by PuppetRuler** [comment]
查出来的好像都是主页的图片,应该是主页图片都能成功加载就能部署成功

**Comment by imsyy** [comment]
已修复 😂
