### ISSUE TITLE
Vercel 部署后绑定国外未备案域名网站一直缓冲

### ISSUE THREAD

**Issue by nlxxtw** [imsyy/vitepress-theme-curve#23]
![image](https://github.com/user-attachments/assets/b314712e-c70c-44c2-b977-734793a7c39d)
大佬，遇到一个奇怪的现象，我用备案国内域名就可以正常进去，是还有啥没设置嘛

**Comment by Daleveral** [comment]
域名是否正确解析到 Vercel ? 以及 vercel 设置里添加域名了吗

**Comment by nlxxtw** [comment]
其他项目可以的，就很奇怪

**Comment by imsyy** [comment]
> 其他项目可以的，就很奇怪

看下控制台哪个资源无法加载呢

**Comment by nlxxtw** [comment]
> > 其他项目可以的，就很奇怪
> 
> 看下控制台哪个资源无法加载呢

![image](https://github.com/user-attachments/assets/bb4f688a-74ef-4a95-a6e2-78b5d65aee7e)
大佬，我看不懂

**Comment by nlxxtw** [comment]
![image](https://github.com/user-attachments/assets/f4b1724e-52a2-435f-beaa-54c78d30d3e1)
右键菜单可以出来

**Comment by imsyy** [comment]
检查下网络环境和浏览器插件吧，部分文件没加载出来
